# Generated by Django 5.1.4 on 2025-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('price_czk', models.IntegerField()),
                ('level', models.CharField(max_length=10)),
                ('level_num', models.IntegerField()),
            ],
            options={
                'ordering': ['date', 'hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='SolarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('watts', models.FloatField(null=True)),
                ('watt_hours_period', models.FloatField()),
                ('watt_hours_cumulative', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_solarda_timesta_19a5fe_idx')],
            },
        ),
    ]
