# Generated by Django 5.1.4 on 2025-01-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('price_czk', models.IntegerField()),
                ('level', models.CharField(max_length=10)),
                ('level_num', models.IntegerField()),
            ],
            options={
                'ordering': ['date', 'hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
    ]
