# Generated by Django 5.1.4 on 2025-01-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('watts', models.FloatField(null=True)),
                ('watt_hours_period', models.FloatField()),
                ('watt_hours_cumulative', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_solarda_timesta_19a5fe_idx')],
            },
        ),
    ]
