# Generated by Django 5.1.4 on 2025-01-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solardata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solardata',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
    ]
