name: Deploy to Production

on:
  push:
    branches:
      - main

concurrency: 
  group: production_environment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H bijec.nti.tul.cz >> ~/.ssh/known_hosts
      
      - name: Deploy with SSH
        run: |
          ssh soda@bijec.nti.tul.cz "\
            cd /var/www/FVE_WebApplication && \
            git pull && \
            docker-compose down --remove-orphans && \
            docker ps -a | grep 'fve_webapplication' | awk '{print $1}' | xargs -r docker rm -f && \
            docker system prune -af && \
            docker-compose up -d --build && \
            docker-compose exec -T backend python manage.py migrate"