name: Deploy to Production

on:
  push:
    branches:
      - main

concurrency: 
  group: production_environment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Stáhne kód
      - uses: actions/checkout@v2

      # Nainstaluj WARP a připoj se
      - name: Install and connect to Cloudflare WARP
        run: |
          curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update && sudo apt-get install -y cloudflare-warp
          warp-cli register
          warp-cli connect

      # Přidej server do known_hosts (přes IPv6)
      - name: Adding Known Hosts
        run: ssh-keyscan -H 2001:718:1c01:21:250:56ff:fe8e:737f >> ~/.ssh/known_hosts

      # Nastav SSH klíč
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      # Deploy přes SSH (přes IPv6)
      - name: Deploy with SSH
        run: |
          ssh soda@[2001:718:1c01:21:250:56ff:fe8e:737f] "\
            cd /var/www/FVE_WebApplication && \
            git pull && \
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S ln -sf /var/www/FVE_WebApplication/nginx/fve.conf /etc/nginx/sites-enabled/fve && \
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S rm -f /etc/nginx/sites-enabled/default && \
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S nginx -t && \
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S systemctl reload nginx && \
            docker-compose -f docker-compose.prod.yml down --remove-orphans && \
            docker ps -a | grep 'fve_webapplication' | awk '{print $1}' | xargs -r docker rm -f && \
            docker system prune -af && \
            docker-compose -f docker-compose.prod.yml up -d --build && \
            docker-compose -f docker-compose.prod.yml exec -T backend python manage.py migrate"